### ISSUE TITLE
Broken Pipe Error

### ISSUE THREAD

**Issue by vazim123** [zhaoziheng/K-Space-Transformer#7]
0%|          | 0/349 [00:00<?, ?it/s]
  0%|          | 0/349 [01:07<?, ?it/s]
Traceback (most recent call last):
  File "E:\Vazim\kspaceTransformer\K-Space-Transformer\main.py", line 196, in <module>
    validSet=validSet, validLoader=validLoader)
  File "E:\Vazim\kspaceTransformer\K-Space-Transformer\train.py", line 99, in train
    for batch in tqdm(trainLoader):
  File "C:\Users\KUDSIT\AppData\Local\Programs\Python\Python37\lib\site-packages\tqdm\std.py", line 1195, in __iter__
    for obj in iterable:
  File "C:\Users\KUDSIT\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\utils\data\dataloader.py", line 435, in __iter__
    return self._get_iterator()
  File "C:\Users\KUDSIT\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\utils\data\dataloader.py", line 381, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\KUDSIT\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\utils\data\dataloader.py", line 1034, in __init__
    w.start()
  File "C:\Users\KUDSIT\AppData\Local\Programs\Python\Python37\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Users\KUDSIT\AppData\Local\Programs\Python\Python37\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\KUDSIT\AppData\Local\Programs\Python\Python37\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\KUDSIT\AppData\Local\Programs\Python\Python37\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\KUDSIT\AppData\Local\Programs\Python\Python37\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
BrokenPipeError: [Errno 32] Broken pipe

Hi! we are trying to train the k-space transformer code in FastMRI dataset. while started  running the script main.py, specificically at the line "for batch in tqdm(trainLoader):" in train.py  the above pasted error  related to broken pipe error gets poped up. May I know, if this has happened before and It would be great to share any solution that could help in resolving this issue.

**Comment by vazim123** [comment]
I have solved the issue. It was relating to the number of workers in the DataLoader utility!
